# Generated by Django 5.2.6 on 2025-09-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image for the blog post.', null=True, upload_to='blog_covers/'),
        ),
    ]
