# Generated by Django 5.2.6 on 2026-04-07 14:38

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, help_text='Optional icon for the service (SVG, PNG, or JPG recommended).', null=True, upload_to='services/icons', validators=[website.models.validate_file_type]),
        ),
    ]
